#!/bin/bash

# Setup Demo Environment on Anvil
echo "🚀 Setting up Prorated Protocol Demo on Anvil..."

# Check if anvil is running
if ! pgrep -f "anvil" > /dev/null; then
    echo "❌ Anvil is not running. Please start Anvil first:"
    echo "   anvil --host 0.0.0.0 --port 8545"
    exit 1
fi

echo "✅ Anvil detected, deploying demo contracts..."

# Deploy demo contracts with improved reliability
echo "📡 Deploying contracts to Anvil..."

# Capture deployment output to parse addresses
DEPLOY_OUTPUT=$(forge script script/DeployDemo.s.sol:DeployDemo \
    --rpc-url http://localhost:8545 \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
    --broadcast \
    --legacy \
    --slow \
    --with-gas-price 2000000000 2>&1)

# Check if deployment was successful
DEPLOY_EXIT_CODE=$?
echo "$DEPLOY_OUTPUT"

if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
    echo "❌ Contract deployment failed!"
    exit 1
fi

# Parse addresses from deployment output and create .env.local
echo "📝 Creating environment file..."
cat > frontend/.env.local << EOF
# Auto-generated by demo deployment
# Generated on $(date)

$(echo "$DEPLOY_OUTPUT" | grep "NEXT_PUBLIC_" | sed 's/^[[:space:]]*//')
EOF

echo "🎉 Demo deployment complete!"

# Verify deployment worked by checking if .env.local was created and has content
if [ ! -f "frontend/.env.local" ]; then
    echo "❌ Environment file not created - deployment may have failed"
    exit 1
fi

if [ ! -s "frontend/.env.local" ]; then
    echo "❌ Environment file is empty - deployment may have failed"
    exit 1
fi

echo "✅ Environment file created successfully"

# Update frontend configuration automatically
echo "🔄 Updating frontend configuration..."
if node script/update-frontend-config.js; then
    echo "✅ Frontend configuration updated successfully!"
else
    echo "❌ Failed to update frontend configuration"
    echo "📋 Manual steps required:"
    echo "1. Copy the environment variables from the output above"
    echo "2. Add them to your frontend/.env.local file"
fi

echo ""
echo "📋 Next steps:"
echo "1. Start your frontend: cd frontend && npm run dev"
echo "2. Visit http://localhost:3000 to test the demo"
echo ""
echo "💡 Demo features:"
echo "- USDC Faucet: Get 1000 USDC per click"
echo "- Auto-approval: No approval transactions needed"
echo "- Time controls: Skip time to test different pool states"
echo "- Pre-funded pools: Test all scenarios immediately"
