#!/bin/bash

# Demo deployment orchestrator script
# Runs each deployment step sequentially and stops on first failure

set -e  # Exit on any error

echo "🚀 Starting Demo Deployment..."

# Configuration
RPC_URL="http://localhost:8545"
SENDER="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# Clear previous env file
echo "🧹 Clearing previous environment file..."
rm -f frontend/.env.local
echo "# Auto-generated by demo deployment" > frontend/.env.local

# Step 1: Deploy MockUSDC
echo "📝 Step 1: Deploying MockUSDC..."
forge script script/demo/01_DeployMockUSDC.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow

if [ $? -ne 0 ]; then
    echo "❌ Step 1 failed: MockUSDC deployment"
    exit 1
fi

echo "✅ Step 1 completed: MockUSDC deployed"

# Step 2: Deploy Proswap
echo "📝 Step 2: Deploying Proswap Infrastructure..."
forge script script/demo/02_DeployProswap.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow

if [ $? -ne 0 ]; then
    echo "❌ Step 2 failed: Proswap deployment"
    exit 1
fi

echo "✅ Step 2 completed: Proswap deployed"

# Step 3: Deploy Prolend Infrastructure
echo "📝 Step 3: Deploying Prolend Infrastructure..."
forge script script/demo/03_DeployProlend.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow \
    --gas-limit 30000000

if [ $? -ne 0 ]; then
    echo "❌ Step 3 failed: Prolend deployment"
    exit 1
fi

echo "✅ Step 3 completed: Prolend deployed"

# Step 4: Deploy Deployer Contracts
echo "📝 Step 4: Deploying Deployer Contracts..."
forge script script/demo/04_DeployDeployers.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow

if [ $? -ne 0 ]; then
    echo "❌ Step 4 failed: Deployer Contracts deployment"
    exit 1
fi

echo "✅ Step 4 completed: Deployer Contracts deployed"

# Step 5: Deploy Demo Factory
echo "📝 Step 5: Deploying Demo Factory..."
forge script script/demo/05_DeployDemoFactory.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow

if [ $? -ne 0 ]; then
    echo "❌ Step 5 failed: Demo Factory deployment"
    exit 1
fi

echo "✅ Step 5 completed: Demo Factory deployed"

# Step 6: Create Demo Pools
echo "📝 Step 6: Creating Demo Pools..."
forge script script/demo/06_CreateDemoPools.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow

if [ $? -ne 0 ]; then
    echo "❌ Step 6 failed: Demo Pools creation"
    exit 1
fi

echo "✅ Step 6 completed: Demo Pools created"

echo ""
echo "🎉 Demo deployment completed successfully!"
echo ""
echo "📋 Environment file generated at: frontend/.env.local"
echo "📋 Contents:"
cat frontend/.env.local
echo ""
echo "🔄 Restart your frontend development server to use the new addresses"
