#!/bin/bash

# Demo deployment orchestrator script
# Runs each deployment step sequentially and stops on first failure
# Extracts contract addresses from forge logs and writes to env file ONLY after successful deployment

set -e  # Exit on any error

echo "🚀 Starting Demo Deployment..."

# Configuration
RPC_URL="http://localhost:8545"
SENDER="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# Helper function to extract address from forge script logs
extract_address() {
    local log_pattern="$1"
    local log_file="$2"
    
    # Extract the address using grep and awk
    grep "$log_pattern" "$log_file" | awk '{print $NF}' | tail -1
}

# Helper function to write to env file
write_to_env() {
    local key="$1"
    local value="$2"
    
    if [ -z "$value" ] || [ "$value" = "" ]; then
        echo "❌ Error: Empty address for $key"
        exit 1
    fi
    
    echo "$key=$value" >> frontend/.env.local
    echo "✅ Added $key=$value to env file"
}

# Clear previous env file and create header
echo "🧹 Clearing previous environment file..."
rm -f frontend/.env.local
echo "# Auto-generated by demo deployment" > frontend/.env.local
echo "# Generated on $(date)" >> frontend/.env.local
echo "" >> frontend/.env.local

# Step 1: Deploy MockUSDC
echo "📝 Step 1: Deploying MockUSDC..."
LOG_FILE_1=$(mktemp)
forge script script/demo/01_DeployMockUSDC.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow 2>&1 | tee "$LOG_FILE_1"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 1 failed: MockUSDC deployment"
    rm -f "$LOG_FILE_1"
    exit 1
fi

# Extract MockUSDC address and write to env
MOCK_USDC_ADDR=$(extract_address "MockUSDC deployed at:" "$LOG_FILE_1")
write_to_env "NEXT_PUBLIC_MOCK_USDC_ADDRESS" "$MOCK_USDC_ADDR"
rm -f "$LOG_FILE_1"

echo "✅ Step 1 completed: MockUSDC deployed at $MOCK_USDC_ADDR"

# Step 2: Deploy Proswap
echo "📝 Step 2: Deploying Proswap Infrastructure..."
LOG_FILE_2=$(mktemp)
forge script script/demo/02_DeployProswap.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow 2>&1 | tee "$LOG_FILE_2"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 2 failed: Proswap deployment"
    rm -f "$LOG_FILE_2"
    exit 1
fi

# Extract Proswap addresses and write to env
PROSWAP_FACTORY_ADDR=$(extract_address "Proswap Factory deployed at:" "$LOG_FILE_2")
PROSWAP_ROUTER_ADDR=$(extract_address "Proswap Router deployed at:" "$LOG_FILE_2")
write_to_env "NEXT_PUBLIC_PROSWAP_FACTORY_ADDRESS" "$PROSWAP_FACTORY_ADDR"
write_to_env "NEXT_PUBLIC_PROSWAP_ROUTER_ADDRESS" "$PROSWAP_ROUTER_ADDR"
rm -f "$LOG_FILE_2"

echo "✅ Step 2 completed: Proswap deployed"
echo "  Factory: $PROSWAP_FACTORY_ADDR"
echo "  Router: $PROSWAP_ROUTER_ADDR"

# Step 3: Deploy Prolend Infrastructure
echo "📝 Step 3: Deploying Prolend Infrastructure..."
LOG_FILE_3=$(mktemp)
forge script script/demo/03_DeployProlend.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow \
    --gas-limit 30000000 2>&1 | tee "$LOG_FILE_3"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 3 failed: Prolend deployment"
    rm -f "$LOG_FILE_3"
    exit 1
fi

# Extract Prolend Factory address and write to env
PROLEND_FACTORY_ADDR=$(extract_address "Prolend Factory deployed at:" "$LOG_FILE_3")
write_to_env "NEXT_PUBLIC_PROLEND_FACTORY_ADDRESS" "$PROLEND_FACTORY_ADDR"
rm -f "$LOG_FILE_3"

echo "✅ Step 3 completed: Prolend deployed at $PROLEND_FACTORY_ADDR"

# Step 4: Deploy Deployer Contracts
echo "📝 Step 4: Deploying Deployer Contracts..."
LOG_FILE_4=$(mktemp)
forge script script/demo/04_DeployDeployers.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow 2>&1 | tee "$LOG_FILE_4"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 4 failed: Deployer Contracts deployment"
    rm -f "$LOG_FILE_4"
    exit 1
fi

# Extract all deployer addresses and write to env
TOKEN_DEPLOYER_ADDR=$(extract_address "TokenDeployer deployed at:" "$LOG_FILE_4")
PAIR_DEPLOYER_ADDR=$(extract_address "PairDeployer deployed at:" "$LOG_FILE_4")
LIQUIDITY_DEPLOYER_ADDR=$(extract_address "LiquidityDeployer deployed at:" "$LOG_FILE_4")
VENFT_DEPLOYER_ADDR=$(extract_address "VeNFTDeployer deployed at:" "$LOG_FILE_4")
GOVERNOR_DEPLOYER_ADDR=$(extract_address "GovernorDeployer deployed at:" "$LOG_FILE_4")
TREASURY_DEPLOYER_ADDR=$(extract_address "TreasuryDeployer deployed at:" "$LOG_FILE_4")
PROLEND_DEPLOYER_ADDR=$(extract_address "ProlendDeployer deployed at:" "$LOG_FILE_4")

write_to_env "NEXT_PUBLIC_TOKEN_DEPLOYER_ADDRESS" "$TOKEN_DEPLOYER_ADDR"
write_to_env "NEXT_PUBLIC_PAIR_DEPLOYER_ADDRESS" "$PAIR_DEPLOYER_ADDR"
write_to_env "NEXT_PUBLIC_LIQUIDITY_DEPLOYER_ADDRESS" "$LIQUIDITY_DEPLOYER_ADDR"
write_to_env "NEXT_PUBLIC_VENFT_DEPLOYER_ADDRESS" "$VENFT_DEPLOYER_ADDR"
write_to_env "NEXT_PUBLIC_GOVERNOR_DEPLOYER_ADDRESS" "$GOVERNOR_DEPLOYER_ADDR"
write_to_env "NEXT_PUBLIC_TREASURY_DEPLOYER_ADDRESS" "$TREASURY_DEPLOYER_ADDR"
write_to_env "NEXT_PUBLIC_PROLEND_DEPLOYER_ADDRESS" "$PROLEND_DEPLOYER_ADDR"
rm -f "$LOG_FILE_4"

echo "✅ Step 4 completed: All 7 Deployer Contracts deployed"

# Step 5: Deploy Demo Factory
echo "📝 Step 5: Deploying Demo Factory..."
LOG_FILE_5=$(mktemp)
forge script script/demo/05_DeployDemoFactory.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow 2>&1 | tee "$LOG_FILE_5"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 5 failed: Demo Factory deployment"
    rm -f "$LOG_FILE_5"
    exit 1
fi

# Extract Demo Factory address and write to env
DEMO_FACTORY_ADDR=$(extract_address "Demo Prorated Factory deployed at:" "$LOG_FILE_5")
write_to_env "NEXT_PUBLIC_PRORATED_FACTORY_ADDRESS" "$DEMO_FACTORY_ADDR"
rm -f "$LOG_FILE_5"

echo "✅ Step 5 completed: Demo Factory deployed at $DEMO_FACTORY_ADDR"

# Step 6: Create Demo Pools
echo "📝 Step 6: Creating Demo Pools..."
LOG_FILE_6=$(mktemp)
forge script script/demo/06_CreateDemoPools.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow 2>&1 | tee "$LOG_FILE_6"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 6 failed: Demo Pools creation"
    rm -f "$LOG_FILE_6"
    exit 1
fi

# Extract pool addresses and write to env
ACTIVE_POOL_ADDR=$(extract_address "Demo Active Pool created at:" "$LOG_FILE_6")
SUCCESSFUL_POOL_ADDR=$(extract_address "Demo Successful Pool created at:" "$LOG_FILE_6")
write_to_env "NEXT_PUBLIC_ACTIVE_POOL_ADDRESS" "$ACTIVE_POOL_ADDR"
write_to_env "NEXT_PUBLIC_SUCCESSFUL_POOL_ADDRESS" "$SUCCESSFUL_POOL_ADDR"
rm -f "$LOG_FILE_6"

echo "✅ Step 6 completed: Demo Pools created"
echo "  Active Pool: $ACTIVE_POOL_ADDR"
echo "  Successful Pool: $SUCCESSFUL_POOL_ADDR"

echo ""
echo "🎉 Demo deployment completed successfully!"
echo ""
echo "📋 Environment file generated at: frontend/.env.local"
echo "📋 Contents:"
cat frontend/.env.local
echo ""
echo "🔄 Restart your frontend development server to use the new addresses"