// SPDX-License-Identifier: Unlicensed
pragma solidity ^0.8.10;

import "forge-std/Script.sol";

/// @title DeploymentHelpers
/// @notice Shared utilities for deployment scripts
/// @dev Provides common functions for verification and environment file management
abstract contract DeploymentHelpers is Script {
    // ============ VERIFICATION HELPERS ============

    /// @notice Verify a contract deployment succeeded
    /// @param contractAddress The deployed contract address
    /// @param contractName Human-readable name for error messages
    function verifyDeployment(
        address contractAddress,
        string memory contractName
    ) internal view {
        require(
            contractAddress != address(0),
            string(abi.encodePacked(contractName, ": zero address"))
        );
        require(
            contractAddress.code.length > 0,
            string(
                abi.encodePacked(contractName, ": deployment failed - no code")
            )
        );
    }

    /// @notice Verify a contract deployment and log success
    /// @param contractAddress The deployed contract address
    /// @param contractName Human-readable name for logging
    function verifyAndLog(
        address contractAddress,
        string memory contractName
    ) internal view {
        verifyDeployment(contractAddress, contractName);
        console.log(
            string(
                abi.encodePacked(contractName, " verified successfully at:")
            ),
            contractAddress
        );
    }

    // ============ ADDRESS PARSING HELPERS ============

    /// @notice Parse an address string (e.g., "0x1234...") to address type
    /// @param addressStr The address string to parse
    /// @return The parsed address
    function parseAddress(
        string memory addressStr
    ) internal pure returns (address) {
        bytes memory addressBytes = bytes(addressStr);
        require(addressBytes.length == 42, "Invalid address length");
        require(
            addressBytes[0] == "0" && addressBytes[1] == "x",
            "Address must start with 0x"
        );

        uint160 result = 0;
        for (uint256 i = 2; i < 42; i++) {
            result *= 16;
            uint8 digit = uint8(addressBytes[i]);

            if (digit >= 48 && digit <= 57) {
                // 0-9
                result += digit - 48;
            } else if (digit >= 65 && digit <= 70) {
                // A-F
                result += digit - 55;
            } else if (digit >= 97 && digit <= 102) {
                // a-f
                result += digit - 87;
            } else {
                revert("Invalid hex character");
            }
        }

        return address(result);
    }

    // ============ ENVIRONMENT FILE HELPERS ============

    /// @notice Write a key-value pair to the environment file (creates or overwrites)
    /// @param key Environment variable name
    /// @param value Contract address value
    function writeEnvFile(string memory key, address value) internal {
        string memory addressStr = addressToString(value);
        string memory envLine = string(
            abi.encodePacked(
                "# Auto-generated by demo deployment\n",
                key,
                "=",
                addressStr,
                "\n"
            )
        );

        vm.writeFile("frontend/.env.local", envLine);
        console.log("Created frontend/.env.local with", key);
    }

    /// @notice Append a key-value pair to the environment file
    /// @param key Environment variable name
    /// @param value Contract address value
    function appendToEnvFile(string memory key, address value) internal {
        string memory addressStr = addressToString(value);
        string memory envLine = string(
            abi.encodePacked(key, "=", addressStr, "\n")
        );

        try vm.readFile("frontend/.env.local") returns (
            string memory existing
        ) {
            // File exists, append to it
            vm.writeFile(
                "frontend/.env.local",
                string(abi.encodePacked(existing, envLine))
            );
        } catch {
            // File doesn't exist, create it with header
            string memory newFile = string(
                abi.encodePacked(
                    "# Auto-generated by demo deployment\n",
                    envLine
                )
            );
            vm.writeFile("frontend/.env.local", newFile);
        }

        console.log("Updated frontend/.env.local with", key);
    }

    /// @notice Convert address to lowercase hex string
    /// @param addr Address to convert
    /// @return Hex string representation (with 0x prefix)
    function addressToString(
        address addr
    ) internal pure returns (string memory) {
        bytes32 value = bytes32(uint256(uint160(addr)));
        bytes memory alphabet = "0123456789abcdef";
        bytes memory str = new bytes(42);
        str[0] = "0";
        str[1] = "x";
        for (uint256 i = 0; i < 20; i++) {
            str[2 + i * 2] = alphabet[uint8(value[i + 12] >> 4)];
            str[3 + i * 2] = alphabet[uint8(value[i + 12] & 0x0f)];
        }
        return string(str);
    }

    // ============ DEPLOYMENT PATTERNS ============

    // ============ SINGLE-PURPOSE HELPER FUNCTIONS ============

    /// @notice Verify a deployment and log success (single purpose)
    /// @param contractAddress The deployed contract address
    /// @param contractName Human-readable name
    function verifyDeploymentAndLog(
        address contractAddress,
        string memory contractName
    ) internal view {
        verifyDeployment(contractAddress, contractName);
        console.log(
            string(
                abi.encodePacked(contractName, " verified successfully at:")
            ),
            contractAddress
        );
    }

    /// @notice Record a contract address in the environment file (single purpose)
    /// @param envKey Environment variable key
    /// @param contractAddress The deployed contract address
    function recordInEnvFile(
        string memory envKey,
        address contractAddress
    ) internal {
        appendToEnvFile(envKey, contractAddress);
    }

    /// @notice Record the first contract address (creates new env file) (single purpose)
    /// @param envKey Environment variable key
    /// @param contractAddress The deployed contract address
    function recordFirstInEnvFile(
        string memory envKey,
        address contractAddress
    ) internal {
        writeEnvFile(envKey, contractAddress);
    }

    // ============ LEGACY COMBINED FUNCTIONS (for backward compatibility) ============

    /// @notice Deploy and verify a contract in one step
    /// @param contractAddress The deployed contract address
    /// @param contractName Human-readable name
    /// @param envKey Environment variable key
    /// @dev DEPRECATED: Use verifyDeploymentAndLog() + recordInEnvFile() for better debugging
    function deployAndRecord(
        address contractAddress,
        string memory contractName,
        string memory envKey
    ) internal {
        verifyDeploymentAndLog(contractAddress, contractName);
        recordInEnvFile(envKey, contractAddress);
    }

    /// @notice Deploy and verify the first contract (creates new env file)
    /// @param contractAddress The deployed contract address
    /// @param contractName Human-readable name
    /// @param envKey Environment variable key
    /// @dev DEPRECATED: Use verifyDeploymentAndLog() + recordFirstInEnvFile() for better debugging
    function deployAndRecordFirst(
        address contractAddress,
        string memory contractName,
        string memory envKey
    ) internal {
        verifyDeploymentAndLog(contractAddress, contractName);
        recordFirstInEnvFile(envKey, contractAddress);
    }

    // ============ COMMON VALIDATIONS ============

    /// @notice Validate that an address is not zero
    /// @param addr Address to validate
    /// @param name Name for error message
    function requireNonZero(address addr, string memory name) internal pure {
        require(
            addr != address(0),
            string(abi.encodePacked(name, " cannot be zero address"))
        );
    }

    /// @notice Validate that a string is not empty
    /// @param str String to validate
    /// @param name Name for error message
    function requireNonEmpty(
        string memory str,
        string memory name
    ) internal pure {
        require(
            bytes(str).length > 0,
            string(abi.encodePacked(name, " cannot be empty"))
        );
    }

    /// @notice Validate that an amount is greater than zero
    /// @param amount Amount to validate
    /// @param name Name for error message
    function requirePositive(uint256 amount, string memory name) internal pure {
        require(
            amount > 0,
            string(abi.encodePacked(name, " must be greater than zero"))
        );
    }
}
