#!/bin/bash

# Test script for Steps 1-2 with new env writing approach

set -e  # Exit on any error

echo "🧪 Testing Steps 1-2 with new env writing approach..."

# Configuration
RPC_URL="http://localhost:8545"
SENDER="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# Helper function to extract address from forge script logs
extract_address() {
    local log_pattern="$1"
    local log_file="$2"
    
    # Extract the address using grep and awk
    grep "$log_pattern" "$log_file" | awk '{print $NF}' | tail -1
}

# Helper function to write to env file
write_to_env() {
    local key="$1"
    local value="$2"
    
    if [ -z "$value" ] || [ "$value" = "" ]; then
        echo "❌ Error: Empty address for $key"
        exit 1
    fi
    
    echo "$key=$value" >> frontend/.env.local
    echo "✅ Added $key=$value to env file"
}

# Clear previous env file and create header
echo "🧹 Clearing previous environment file..."
rm -f frontend/.env.local
echo "# Auto-generated by demo deployment" > frontend/.env.local
echo "# Generated on $(date)" >> frontend/.env.local
echo "" >> frontend/.env.local

# Step 1: Deploy MockUSDC
echo "📝 Step 1: Deploying MockUSDC..."
LOG_FILE_1=$(mktemp)
forge script script/demo/01_DeployMockUSDC.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow 2>&1 | tee "$LOG_FILE_1"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 1 failed: MockUSDC deployment"
    rm -f "$LOG_FILE_1"
    exit 1
fi

# Extract MockUSDC address and write to env
MOCK_USDC_ADDR=$(extract_address "MockUSDC deployed at:" "$LOG_FILE_1")
write_to_env "NEXT_PUBLIC_MOCK_USDC_ADDRESS" "$MOCK_USDC_ADDR"
rm -f "$LOG_FILE_1"

echo "✅ Step 1 completed: MockUSDC deployed at $MOCK_USDC_ADDR"

# Step 2: Deploy Proswap
echo "📝 Step 2: Deploying Proswap Infrastructure..."
LOG_FILE_2=$(mktemp)
forge script script/demo/02_DeployProswap.s.sol \
    --rpc-url $RPC_URL \
    --broadcast \
    --sender $SENDER \
    --private-key $PRIVATE_KEY \
    --slow 2>&1 | tee "$LOG_FILE_2"

if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "❌ Step 2 failed: Proswap deployment"
    rm -f "$LOG_FILE_2"
    exit 1
fi

# Extract Proswap addresses and write to env
PROSWAP_FACTORY_ADDR=$(extract_address "Proswap Factory deployed at:" "$LOG_FILE_2")
PROSWAP_ROUTER_ADDR=$(extract_address "Proswap Router deployed at:" "$LOG_FILE_2")
write_to_env "NEXT_PUBLIC_PROSWAP_FACTORY_ADDRESS" "$PROSWAP_FACTORY_ADDR"
write_to_env "NEXT_PUBLIC_PROSWAP_ROUTER_ADDRESS" "$PROSWAP_ROUTER_ADDR"
rm -f "$LOG_FILE_2"

echo "✅ Step 2 completed: Proswap deployed"
echo "  Factory: $PROSWAP_FACTORY_ADDR"
echo "  Router: $PROSWAP_ROUTER_ADDR"

echo ""
echo "🎉 Steps 1-2 completed successfully!"
echo ""
echo "📋 Environment file generated at: frontend/.env.local"
echo "📋 Contents:"
cat frontend/.env.local
